
services:
  backend:
    build: ./beelicious_be
    container_name: backend
    restart: always
    env_file:
      - ./beelicious_be/.env
    ports:
      - "5000:5000"

  frontend:
    build: ./beelicious_fe
    container_name: frontend
    restart: always
    ports:
      - "3005:3005" 
    depends_on:
      - backend